name: Save Cache

on:
  repository_dispatch:
    types: [save_cache]  # Esse workflow será acionado pelo primeiro workflow

jobs:
  save-cache:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Verificar se bot_state.json foi gerado
        run: ls -la data/bot_state.json
        if: always()

      - name: Cache bot state
        uses: actions/cache@v3
        with:
          path: data/bot_state.json
          key: bot-state-cache-${{ runner.os }}-v1

      # Passo 4: Salvar o estado no cache
      - name: Save bot state cache
        uses: actions/cache@v3
        with:
          path: data/bot_state.json  # Caminho correto para o arquivo
          key: bot-state-cache-${{ runner.os }}-v1
